translate_dict = {
    "SuckHard's Calculators": "SuckHard的计算器",
    "SuckHard's Cubing Calculator": "SuckHard的魔方计算器",
    "SuckHard's Maplestory Tools": "SuckHard的冒险岛工具箱",
    "Cubing": "魔方",
    "(current)": "（当前）",
    "WSE": "三大件",
    "Starforcing": "星之力",
    "Hyper Stat": "超级属性",
    "Legion": "联盟",
    "Flaming": "火花",
    "Stat Equivalence": "属性等价",
    "Inner Ability": "内在能力",
    "Theoretical Probability": "理论概率",
    "Item Category": "道具类型",
    "Accessory": "首饰",
    "Badge": "徽章",
    "Belt": "腰带",
    "Bottom": "裙裤",
    "Cape": "披风",
    "Emblem": "纹章",
    "Gloves": "手套",
    "Hat": "帽子",
    "Heart": "心脏",
    "Overall": "套服",
    "Top": "上衣",
    "Secondary": "副武器",
    "Shoes": "鞋子",
    "Shoulder": "护肩",
    "Weapon": "武器",
    "Cube Type": "魔方类型",
    "Current Tier": "当前阶级",
    "Item Level": "道具等级",
    "Desired Tier": "目标阶级",
    "Stat Type": "属性类型",
    "Normal": "普通",
    "Max HP (Demon Avenger)": "最大血量（白毛）",
    "Desired Stat": "目标属性",
    "Any": "任意",
    "Number of Trials": "尝试次数",
    "Calculate": "计算",
    "Flaming Information": "火花信息",
    "Class": "职业",
    "Other": "其它",
    "Dual Blade": "暗影双刀",
    "Cadena": "卡德纳",
    "Shadower": "侠盗",
    "Xenon": "尖兵",
    "Demon Avenger": "白毛",
    "Armor": "防具",
    "Flame Type": "火花类型",
    "Flame-Advantaged Item": "特殊类火花道具",
    "Stat Equivalences": "属性等价",
    "Use my": "使用我的",
    "Stat Equivalent Calculator": "属性等价计算器",
    "to determine the ratios for your character. Leave this section alone if you are unsure.</h5>":
        "来为你的角色确定比例。如果你不确定，请不要理会本部分",
    "1 All Stat % = ": "1全属性%=",
    "Main Stat": "主属性",
    "Secondary Stat": "副属性",
    "LUK": "运气",
    "DEX": "敏捷",
    "STR": "力量",
    "1 Attack = ": "1攻击力=",
    "1 Main Stat =": "1主属性=",
    "HP": "血量",
    "Attack Tier": "攻击力属性等级",
    "HP Tier": "血量属性等级",
    "Calculator": "计算器",
    "This tool is designed to optimize your hyper stats against end-game bosses.":
        "该工具旨在优化你的超级属性，以对抗游戏的终极Boss",
    "SuckHard's Star Force Calculator": "SuckHard的星之力计算器",
    "Experimental Probability": "实验概率",
    "Tyrant": "暴君",
    "No star catching": "取消抓星星",
    "+4.5% multiplicative": "+4.5%倍率",
    "Safeguard": "保护",
    "No safeguard": "不保护",
    "Item Level:": "道具等级：",
    "Item Type:": "道具类型：",
    "Star Catching:": "抓星星：",
    "Safeguard:": "保护：",
    "Current Stars:": "当前星数：",
    "Target Stars:": "目标星数：",
    "MVP Discount:": "MVP折扣：",
    "None": "无",
    "MVP Silver (3% off 1 to 16)": "白银MVP（1-16星3%折扣）",
    "MVP Gold (5% off 1 to 16)": "黄金MVP（1-16星5%折扣）",
    "MVP Diamond (10% off 1 to 16)": "钻石MVP（1-16星10%折扣）",
    "Server:": "服务器：",
    "<p>Event:": "<p>活动：",
    "Non-Reboot:": "非R区：",
    "30% off": "30%折扣",
    "+2 Stars (Up to 10 stars)": "一次升2星（10星之前）",
    'Number of Trials: <input type="number" id="trials" value="1000" />':
        '尝试次数：<input type="number" id="trials" value="1000" />',
    '<ion-icon name="star-sharp"></ion-icon>Star Force': '<ion-icon name="star-sharp"></ion-icon>星之力',
    "Average cost: ${averageCost.toLocaleString()}<br />": "消耗平均值：${averageCost.toLocaleString()}<br />",
    "Median cost: ${medianCost.toLocaleString()}<br />": "消耗中位数：${averageCost.toLocaleString()}<br />",
    "Average cost: ${average_mesos}<br />": "消耗平均值：${average_mesos}<br />",
    "Median cost: ${median_cost}<br />": "消耗中位数：${median_cost}<br />",
    "Range of cost: ${min_cost} - ${max_cost}<br />": "消耗区间：${min_cost} - ${max_cost}<br />",
    "75% chance within ${seventy_fifth_percentile} ${currency}<br />":
        "75%置信概率在${seventy_fifth_percentile} ${currency}以内<br />",
    "85% chance within ${eighty_fifth_percentile} ${currency}<br />":
        "85%置信概率在${eighty_fifth_percentile} ${currency}以内<br />",
    "95% chance within ${ninty_fifth_percentile} ${currency}<br />":
        "95%置信概率在${ninty_fifth_percentile} ${currency}以内<br />",
    "Average booms: ${average_booms}<br />": "爆炸次数平均值：${average_booms}<br />",
    "Median booms: ${median_booms}<br />": "爆炸次数中位数：${median_booms}<br />",
    "Range of booms: ${min_booms} - ${max_booms}<br />": "爆炸次数区间：${min_booms} - ${max_booms}<br />",
    "75% chance within ${seventy_fifth_percentile_boom} booms<br />":
        "75%置信概率爆炸次数在${seventy_fifth_percentile_boom}以内<br />",
    "85% chance within ${eighty_fifth_percentile_boom} booms<br />":
        "85%置信概率爆炸次数在${eighty_fifth_percentile_boom}以内<br />",
    "95% chance within ${ninty_fifth_percentile_boom} booms<br />":
        "95%置信概率爆炸次数在${ninty_fifth_percentile_boom}以内<br />",
    "text: 'Frequency Histogram',": "text: '频率直方图',",
    "return `${context.raw} occurrences (${context.raw*100/trialsAmount}%)`;":
        "return `${context.raw}次 (${context.raw*100/trialsAmount}%)`;",
    "text: 'Boom Amount',": "text: '爆炸次数',",
    "75% chance within ${costSevenFive.toLocaleString()} mesos<br />":
        "75%置信概率在${costSevenFive.toLocaleString()} mesos 以内<br />",
    "85% chance within ${costEightFive.toLocaleString()} mesos<br />":
        "85%置信概率在${costEightFive.toLocaleString()} mesos 以内<br />",
    "95% chance within ${costNineFive.toLocaleString()} mesos<br />":
        "95%置信概率在${costNineFive.toLocaleString()} mesos 以内<br />",
    "Average cubes: ${averageCubeCount.toLocaleString()} ${cubeType} cubes<br />":
        "魔方数量平均值: ${averageCubeCount.toLocaleString()} ${cubeType} cubes<br />",
    "Median cubes: ${medianCubeCount.toLocaleString()} ${cubeType} cubes<br />":
        "魔方数量中位数: ${medianCubeCount.toLocaleString()} ${cubeType} cubes<br />",
    "75% chance within ${cubeSevenFive.toLocaleString()} ${cubeType} cubes<br />":
        "75%置信概率在${cubeSevenFive.toLocaleString()} ${cubeType} cubes 以内<br />",
    "85% chance within ${cubeEightFive.toLocaleString()} ${cubeType} cubes<br />":
        "85%置信概率在${cubeEightFive.toLocaleString()} ${cubeType} cubes 以内<br />",
    "95% chance within ${cubeNineFive.toLocaleString()} ${cubeType} cubes<br />":
        "95%置信概率在${cubeNineFive.toLocaleString()} ${cubeType} cubes 以内<br />",
    '<ion-icon name="cube-sharp"></ion-icon>Cubing': '<ion-icon name="cube-sharp"></ion-icon>洗魔方',
    "Cubing Information": "洗魔方数据",
    "Desired Stats": "目标属性",
    '<option value="allStat">All Stat (including 1/3rd of STR, LUK, and DEX for Xenon)</option>':
        '<option value="allStat">全属性（尖兵，1点力量运气敏捷算作1/3点全属性）</option>',
}
